# Generated by Django 5.1.4 on 2024-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_transaction_fine_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
